xichen2020/eventdb

glide.lock, server/http/handlers/handlers.go, server/http/handlers/options.go, server/http/handlers/response.go, server/http/handlers/service.go, server/http/options.go, server/http/server.go, storage/database.go, storage/options.go
cc @notbdu 
This PR adds HTTP server w/ write API.
=> HTTP server w/ write API

glide.lock, glide.yaml, parser/json/parser_benchmark_test.go, sharding/shardset.go, storage/database.go, storage/namespace.go, storage/segment.go, storage/shard.go, x/hash/hash.go, x/unsafe/convert.go
cc @notbdu 
This PR adds the initial logic to bootstrap the database write path.
=> Bootstrap database write path

encoding/bool/encoding.go, encoding/common/common.go, encoding/double/encoding.go, encoding/int/encoding.go, glide.lock
- Adds iface def for `bool` and `double`.
- Updates iface def for `string` and `int`.
NOTE: Need to discuss null encoder/decoder.
=> Add iface defs for all types.

persist/fs/manager.go, persist/fs/options.go, persist/fs/writer.go, persist/fs/writer_test.go, persist/persist.go, storage/segment.go
cc @notbdu 
This PR adds logic to write raw documents to segment files as a configurable internal field in the segment.
=> Write raw documents to segment files

encoding/time_decode.go, encoding/time_encode.go, encoding/time_iterator.go, event/field/field.go, persist/fs/manager.go, persist/fs/options.go, persist/fs/writer.go, persist/persist.go, server/http/handlers/service.go, storage/database.go, storage/options.go, storage/segment.go
cc @notbdu 
This PR adds logic to persist timestamp field more efficiently.
=> Write timestamp field

parser/json/parser.go, persist/fs/options.go, persist/fs/writer.go
cc @notbdu 
This PR supports encoding timestamps with configured precisions.
=> Support configuring timestamp precisions

server/http/handlers/service.go, storage/database.go
cc @notbdu 
This PR adds logic to support writing a batch of events, reusing the existing `write` endpoint.
=> Support writing a batch of events

config/config.yaml, services/eventdb/config/database.go, storage/mediator.go, storage/options.go, storage/segment.go, storage/shard.go
cc @notbdu 
This PR adds logic to support configuring maximum number of documents per segment.
=> Support configuring maximum number of documents per segment

query/calculation_op.go, query/filter_combinator.go, query/filter_op.go, query/query.go, query/result.go, query/sort_order.go, query/time_unit.go
cc @notbdu 
This PR adds high-level data types for query.
=> Add high-level query types

query/filter_op.go, query/query.go, query/time_unit.go
cc @notbdu 
This PR adds logic to parse a raw query into a `ParsedQuery` object, which will be passed to the database for query execution.
=> Query parsing

document/field/field.go, index/bool_field.go, index/docs_field.go, index/docs_field_test.go, index/double_field.go, index/int_field.go, index/null_field.go, index/string_field.go, index/time_field.go, persist/fs/files.go, persist/fs/manager.go, persist/fs/reader.go, persist/fs/retriever.go, persist/fs/writer.go, persist/persist.go, services/eventdb/config/database.go, storage/immutable_segment.go, storage/mutable_segment.go, storage/options.go, storage/shard.go, x/hash/hash.go
cc @notbdu 
This PR adds logic and a few APIs to construct fields from mmap'ed regions and merging them into in-memory cached field maps on demand during query execution.
=> Read path part 10: Memory mapping files into memory and construct doc fields from mmaped data

glide.lock, storage/shard.go
Get the first element greater than or equal to the lookup key.
=> Use forked skiplist impl.

query/raw_result.go
cc @notbdu @black-adder 
This PR implements `Add` and `AddBatch` for raw results.
=> Implement Add and AddBatch for raw results

query/grouped_result.go, query/raw_result.go, query/result_group.go, storage/immutable_segment.go, storage/segment_query.go
cc @black-adder @notbdu 
This PR adds support for unordered multi-key group by query.
=> Support unordered multi-key groupBy query

persist/fs/writer.go
- Initialize type specific encoders.
- Add segment writer close logic.
=> Initialize type specific encoders and add close logic.

glide.lock, glide.yaml, persist/fs/manager.go, persist/fs/retriever.go, server/http/handlers/service.go, services/eventdb/config/database.go, storage/database.go, storage/namespace.go, storage/sealed_segment.go, storage/shard.go, storage/shard_test.go
Adds instrumentation to storage/database.
=> Instrument Storage/Database

storage/database.go
Since the `Write` method doesn't get called, we need to instrument the `WriteBatch` method.
=> Instrument database WriteBatch method

query/grouped_result.go
=> Return JSON marshallable empty response.

storage/immutable_segment.go, values/decoding/compressed_reader.go, values/decoding/dictionary_based_string_iterator.go, values/decoding/int_decode.go, values/decoding/raw_size_string_iterator.go, values/decoding/string_decode.go, values/decoding/varint_int_iterator.go, values/encoding/string_encode.go, x/io/reader.go
Performs housekeeping ops to release resources used by gozstd's compressed reader/writer.
=> Perform housekeeping on zstd compressed reader/writers.

index/field/docs_field.go, index/field/docs_field_test.go
No wonder the benchmarks made no sense
=> Stop rebuilding IntFieldBuilder on each Add call

storage/segment_query.go
Fixes group by queries where operations (e.g. `COUNT`) do not require any fields.
=> Fix group by query.

integration/client.go, integration/query_result.go, integration/time_bucket_no_filter_test.go, integration/time_bucket_with_filter_test.go, query/grouped_query.go, query/raw_query.go, query/time_bucket_query.go, query/time_unit.go, storage/immutable_segment.go, storage/mutable_segment.go, storage/segment_query.go
cc @notbdu @black-adder @cw9 
This PR adds integration tests for time bucket queries.
=> Add integration tests for time bucket queries
